#!/bin/bash

[[ -z "$1" ]] && { echo "You need to define a page name! The generation script has been stopped."; exit 1; }

PAGENAME=$1-page

ng g m pages/$PAGENAME --routing || { echo "This page already exists! The generation script has been stopped."; exit 2; }
ng g c pages/$PAGENAME || { echo "This page already exists! The generation script has been stopped."; exit 2; }

COMPONENT="${1^}"PageComponent
APPFOLDER=$PWD/src/app
ROUTINGFILE="$APPFOLDER/pages/$1-page/$1-page-routing.module.ts"

sed -i "s/\[\]/\[\{path:'',component:$COMPONENT\}\]/" "$ROUTINGFILE"

sed -i "1iimport \{ $COMPONENT \} from './$1-page.component';\n" "$ROUTINGFILE"

sed -i "s/Routes = \[/Routes = \[\{path:'$1',loadChildren:'.\/pages\/$1-page\/$1-page.module#${1^}PageModule'\},/" "$APPFOLDER/nav-routing.ts"
